"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type School={id:string;name:string}; type Semester={id:string;school_id:string;name:string};
type ClassRow={id:string;school_id:string;semester_id:string;name:string};
type Student={id:string;class_id:string;name:string};
type Metric={id:string;session_id:string;name:string;display_order:number};
type RecordRow={id:string;session_id:string;student_id:string;attendance:string;notes:string|null;confidence:number|null;source:string};
type ValueRow={id:string;student_session_record_id:string;assessment_metric_id:string;raw_value:string|null;confidence:number|null};
type Session={id:string;class_id:string;session_date:string;source:string;review_status:string;student_count_present:number|null;metrics:Metric[];records:RecordRow[]};
type SheetMeta={school_name?:string;class_name?:string;day_time?:string;lead_coach?:string;teacher?:string;assistant?:string;theme?:string;focus_training?:string;rules?:string;around_world?:string;notes?:string;fingerprint?:string};
type DraftRecord={student_name:string;student_id:string;attendance:string;values:Record<string,string>;confidence:number};
type DraftSession={date:string;metrics:string[];records:DraftRecord[]};
type DraftMatrix={sheet:SheetMeta;students:string[];sessions:DraftSession[]};

const db=createClient(); const today=()=>new Date().toISOString().slice(0,10);
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
function distance(a:string,b:string){const m=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=m[0];m[0]=i;for(let j=1;j<=b.length;j++){const old=m[j];m[j]=Math.min(m[j]+1,m[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return m[b.length]}
function matchStudent(name:string,students:Student[]){const n=norm(name);let best:Student|undefined,score=Infinity;for(const s of students){const d=distance(n,norm(s.name))/Math.max(n.length,norm(s.name).length,1);if(d<score){score=d;best=s}}return score<=.28?best:undefined}

export default function ReportApp(){
 const [schools,setSchools]=useState<School[]>([]),[semesters,setSemesters]=useState<Semester[]>([]),[classes,setClasses]=useState<ClassRow[]>([]),[students,setStudents]=useState<Student[]>([]),[sessions,setSessions]=useState<Session[]>([]),[values,setValues]=useState<ValueRow[]>([]);
 const [schoolId,setSchoolId]=useState(""),[semesterId,setSemesterId]=useState(""),[classId,setClassId]=useState("");
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[modal,setModal]=useState<"session"|"upload"|"roster"|"structure"|null>(null),[extracting,setExtracting]=useState(false),[draft,setDraft]=useState<DraftMatrix|null>(null);
 const activeSchool=schools.find(x=>x.id===schoolId),activeSemester=semesters.find(x=>x.id===semesterId),activeClass=classes.find(x=>x.id===classId),visibleSemesters=semesters.filter(x=>x.school_id===schoolId),visibleClasses=classes.filter(x=>x.semester_id===semesterId);

 const loadBase=useCallback(async()=>{setLoading(true);const [a,b,c]=await Promise.all([db.from("schools").select("*").order("created_at"),db.from("semesters").select("*").order("created_at"),db.from("classes").select("*").order("created_at")]);const er=a.error||b.error||c.error;if(er){setError(er.message);setLoading(false);return}setSchools(a.data||[]);setSemesters(b.data||[]);setClasses(c.data||[]);const sid=schoolId||a.data?.[0]?.id||"",sem=semesterId||b.data?.find(x=>x.school_id===sid)?.id||"";setSchoolId(sid);setSemesterId(sem);setClassId(classId||c.data?.find(x=>x.semester_id===sem)?.id||"");setLoading(false)},[schoolId,semesterId,classId]);
 const loadClass=useCallback(async()=>{if(!classId){setStudents([]);setSessions([]);setValues([]);return}const [st,se]=await Promise.all([db.from("students").select("*").eq("class_id",classId).order("created_at"),db.from("sessions").select("*").eq("class_id",classId).order("session_date")]);if(st.error||se.error){setError((st.error||se.error)!.message);return}const sessionIds=(se.data||[]).map(x=>x.id);let metrics:Metric[]=[],records:RecordRow[]=[],vals:ValueRow[]=[];if(sessionIds.length){const [m,r]=await Promise.all([db.from("assessment_metrics").select("*").in("session_id",sessionIds).order("display_order"),db.from("student_session_records").select("*").in("session_id",sessionIds)]);if(m.error||r.error){setError((m.error||r.error)!.message);return}metrics=m.data||[];records=r.data||[];const recordIds=records.map(x=>x.id);if(recordIds.length){const v=await db.from("student_metric_values").select("*").in("student_session_record_id",recordIds);if(v.error){setError(v.error.message);return}vals=v.data||[]}}setStudents(st.data||[]);setSessions((se.data||[]).map(s=>({...s,metrics:metrics.filter(m=>m.session_id===s.id),records:records.filter(r=>r.session_id===s.id)})));setValues(vals)},[classId]);
 useEffect(()=>{loadBase()},[]);useEffect(()=>{loadClass()},[loadClass]);useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(""),4000);return()=>clearTimeout(t)}},[notice]);
 function chooseSchool(id:string){setSchoolId(id);const sem=semesters.find(x=>x.school_id===id)?.id||"";setSemesterId(sem);setClassId(classes.find(x=>x.semester_id===sem)?.id||"")}function chooseSemester(id:string){setSemesterId(id);setClassId(classes.find(x=>x.semester_id===id)?.id||"")}

 async function persistMatrix(matrix:DraftMatrix,source:"manual"|"ai_extracted"){
  setError("");let sheetId:string|undefined;
  if(matrix.sheet&&Object.keys(matrix.sheet).length){const fp=matrix.sheet.fingerprint||`${classId}:${norm(matrix.sheet.class_name||activeClass?.name||"")}`;const prior=await db.from("report_sheets").select("id").eq("class_id",classId).eq("sheet_fingerprint",fp).maybeSingle();const payload={class_id:classId,school_label:matrix.sheet.school_name||null,group_label:matrix.sheet.class_name||null,day_time:matrix.sheet.day_time||null,lead_coach:matrix.sheet.lead_coach||null,teacher:matrix.sheet.teacher||null,assistant:matrix.sheet.assistant||null,theme:matrix.sheet.theme||null,focus_training:matrix.sheet.focus_training||null,rules:matrix.sheet.rules||null,around_world:matrix.sheet.around_world||null,notes:matrix.sheet.notes||null,sheet_fingerprint:fp};if(prior.data){sheetId=prior.data.id;await db.from("report_sheets").update(payload).eq("id",sheetId)}else{const ins=await db.from("report_sheets").insert(payload).select("id").single();if(ins.error)throw ins.error;sheetId=ins.data.id}}
  for(const ds of matrix.sessions){const existing=await db.from("sessions").select("id").eq("class_id",classId).eq("session_date",ds.date).maybeSingle();let sessionId=existing.data?.id;if(!sessionId){const ins=await db.from("sessions").insert({class_id:classId,report_sheet_id:sheetId||null,session_date:ds.date,source,review_status:"edited"}).select("id").single();if(ins.error)throw ins.error;sessionId=ins.data.id}
   const metricIds:Record<string,string>={};for(let i=0;i<ds.metrics.length;i++){const name=ds.metrics[i].trim();if(!name)continue;const found=await db.from("assessment_metrics").select("id").eq("session_id",sessionId).eq("name",name).maybeSingle();if(found.data)metricIds[name]=found.data.id;else{const ins=await db.from("assessment_metrics").insert({session_id:sessionId,name,display_order:i}).select("id").single();if(ins.error)throw ins.error;metricIds[name]=ins.data.id}}
	   for(const dr of ds.records){let studentId=dr.student_id;if(!studentId){const matched=matchStudent(dr.student_name,students);studentId=matched?.id||""}if(!studentId){const ins=await db.from("students").insert({class_id:classId,name:dr.student_name}).select("id").single();if(ins.error)throw ins.error;studentId=ins.data.id}const prior=await db.from("student_session_records").select("id").eq("session_id",sessionId).eq("student_id",studentId).maybeSingle();let recordId=prior.data?.id;if(recordId){await db.from("student_session_records").update({attendance:dr.attendance||"unknown",source,confidence:dr.confidence,review_status:"edited"}).eq("id",recordId)}else{const ins=await db.from("student_session_records").insert({session_id:sessionId,student_id:studentId,attendance:dr.attendance||"unknown",source,confidence:dr.confidence,review_status:"edited"}).select("id").single();if(ins.error)throw ins.error;recordId=ins.data.id}for(const [metricName,raw] of Object.entries(dr.values)){const metricId=metricIds[metricName];if(!metricId||raw==="")continue;const existingValue=await db.from("student_metric_values").select("id").eq("student_session_record_id",recordId).eq("assessment_metric_id",metricId).maybeSingle();const payload={raw_value:raw,numeric_value:Number.isFinite(Number(raw))?Number(raw):null,confidence:dr.confidence,review_status:"edited"};if(existingValue.data)await db.from("student_metric_values").update(payload).eq("id",existingValue.data.id);else await db.from("student_metric_values").insert({...payload,student_session_record_id:recordId,assessment_metric_id:metricId})}}
	   const refreshed=await db.from("students").select("*").eq("class_id",classId).order("created_at");if(refreshed.error)throw refreshed.error;students.splice(0,students.length,...(refreshed.data||[]));
	  }
 }
 async function saveManual(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),date=String(f.get("date")),metrics=String(f.get("metrics")).split(",").map(x=>x.trim()).filter(Boolean),records=students.map(s=>({student_name:s.name,student_id:s.id,attendance:String(f.get(`attendance:${s.id}`)||"unknown"),values:Object.fromEntries(metrics.map(m=>[m,String(f.get(`value:${s.id}:${m}`)||"")])),confidence:1}));try{await persistMatrix({sheet:{class_name:activeClass?.name},students:students.map(s=>s.name),sessions:[{date,metrics,records}]},"manual");setModal(null);setNotice("Session saved to the matrix.");loadClass()}catch(x){setError(x instanceof Error?x.message:"Could not save. Please retry.")}}
 async function upload(file?:File){if(!file)return;if(!/^image\/(png|jpeg)$/.test(file.type)){setError("Please upload an image file (PNG, JPG).");return}setExtracting(true);setError("");try{const body=new FormData();body.append("image",file);body.append("classId",classId);const r=await fetch("/api/extract",{method:"POST",body}),json=await r.json();if(!r.ok)throw new Error(json.error);const matrix:DraftMatrix={sheet:json.sheet||{},students:json.students||[],sessions:(json.sessions||[]).map((s:DraftSession)=>({...s,records:(s.records||[]).map(dr=>({...dr,student_id:matchStudent(dr.student_name,students)?.id||""}))}))};setDraft(matrix);if(!matrix.sessions.length)setError("No completed session dates detected.")}catch(x){setError(x instanceof Error?x.message:"Extraction failed. You can add a session manually.")}finally{setExtracting(false)}}
 async function saveDraft(){if(!draft)return;try{await persistMatrix(draft,"ai_extracted");setModal(null);setDraft(null);setNotice("Sheet matrix saved; existing dates were updated without duplicates.");loadClass()}catch(x){setError(x instanceof Error?x.message:"Could not save. Please retry.")}}
 async function saveRoster(e:FormEvent<HTMLFormElement>){e.preventDefault();const name=String(new FormData(e.currentTarget).get("name")).trim();const r=await db.from("students").insert({class_id:classId,name});if(r.error)setError(r.error.message);else{e.currentTarget.reset();loadClass()}}
 async function addStructure(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),kind=String(f.get("kind")),name=String(f.get("name")).trim();let r;if(kind==="school")r=await db.from("schools").insert({name});else if(kind==="semester")r=await db.from("semesters").insert({name,school_id:schoolId});else r=await db.from("classes").insert({name,school_id:schoolId,semester_id:semesterId});if(r.error)setError(r.error.message);else{setModal(null);loadBase()}}
 const recordBy=useMemo(()=>new Map(sessions.flatMap(s=>s.records.map(r=>[`${s.id}:${r.student_id}`,r]))),[sessions]);const valueBy=useMemo(()=>new Map(values.map(v=>[`${v.student_session_record_id}:${v.assessment_metric_id}`,v])),[values]);
 if(loading)return <main className="center"><span className="spinner"/>Loading report matrix…</main>;
 return <main className="shell"><aside><div className="brand"><span>SR</span><div><b>School Reports</b><small>Multi-date coach sheets</small></div></div><label>School</label><select value={schoolId} onChange={e=>chooseSchool(e.target.value)}>{schools.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label>Semester</label><select value={semesterId} onChange={e=>chooseSemester(e.target.value)}>{visibleSemesters.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="nav-title"><label>Class tabs</label><button className="icon" onClick={()=>setModal("structure")}>+</button></div><nav>{visibleClasses.map(x=><button className={classId===x.id?"active":""} onClick={()=>setClassId(x.id)} key={x.id}>{x.name}</button>)}</nav><button className="ghost full" onClick={()=>setModal("structure")}>+ Add workspace item</button></aside>
 <section className="content"><header><div><p className="crumb">{activeSchool?.name} / {activeSemester?.name}</p><h1>{activeClass?.name||"Choose a class"}</h1><p>{students.length} roster students · {sessions.length} session dates</p></div><div className="actions"><button className="ghost" onClick={()=>setModal("roster")}>Manage roster</button><button className="ghost" onClick={()=>setModal("session")}>+ Add session</button><button className="primary" onClick={()=>{setDraft(null);setModal("upload")}}>Upload sheet</button></div></header>{notice&&<div className="notice">✓ {notice}</div>}{error&&<div className="error">{error}<button onClick={()=>setError("")}>×</button></div>}<div className="tabs">{visibleClasses.map(x=><button className={classId===x.id?"selected":""} onClick={()=>setClassId(x.id)} key={x.id}>{x.name}</button>)}</div>
 <div className="card matrix-card"><div className="card-head"><div><h2>Class session matrix</h2><p>One roster · multiple dates · date-specific assessments</p></div></div>{sessions.length===0?<Empty/>:<div className="table-wrap"><table className="matrix"><thead><tr><th rowSpan={2} className="sticky-col">Student</th>{sessions.map(s=><th key={s.id} colSpan={1+s.metrics.length} className="date-group">{new Date(s.session_date+"T00:00:00").toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}</th>)}</tr><tr>{sessions.flatMap(s=>[<th key={`${s.id}:a`}>Attendance</th>,...s.metrics.map(m=><th key={m.id}>{m.name}</th>)])}</tr></thead><tbody>{students.map(st=><tr key={st.id}><td className="sticky-col"><b>{st.name}</b></td>{sessions.flatMap(s=>{const rec=recordBy.get(`${s.id}:${st.id}`);return[<td key={`${s.id}:${st.id}:a`}><span className={`pill ${rec?.attendance||"unknown"}`}>{rec?.attendance||"—"}</span></td>,...s.metrics.map(m=><td key={`${s.id}:${st.id}:${m.id}`} className={valueBy.get(`${rec?.id}:${m.id}`)?.confidence!==null&&Number(valueBy.get(`${rec?.id}:${m.id}`)?.confidence)<.6?"uncertain":""}>{rec?valueBy.get(`${rec.id}:${m.id}`)?.raw_value||"—":"—"}</td>)]})}</tr>)}</tbody></table></div>}</div></section>
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><div className="modal wide-modal"><button className="close" onClick={()=>setModal(null)}>×</button>{modal==="session"&&<ManualSession students={students} save={saveManual}/>} {modal==="upload"&&<UploadReview draft={draft} students={students} extracting={extracting} upload={upload} setDraft={setDraft} save={saveDraft}/>} {modal==="roster"&&<><h2>Student roster</h2><form className="inline" onSubmit={saveRoster}><input name="name" placeholder="Student name" required/><button className="primary">Add</button></form><div className="roster">{students.map(s=><div key={s.id}>{s.name}</div>)}</div></>} {modal==="structure"&&<StructureForm save={addStructure}/>}</div></div>}</main>
}
function Empty(){return <div className="empty"><div className="empty-icon">▦</div><h3>No sessions yet</h3><p>Upload a report sheet or add a session manually.</p></div>}
function ManualSession({students,save}:{students:Student[];save:(e:FormEvent<HTMLFormElement>)=>void}){const [metrics,setMetrics]=useState(["Focus Training","Right Behavior"]);return <><h2>Add session</h2><p>Create a date group and fill its attendance and assessment cells.</p><form onSubmit={save}><div className="grid"><label>Date<input type="date" name="date" defaultValue={today()} required/></label><label>Metrics, comma separated<input name="metrics" value={metrics.join(", ")} onChange={e=>setMetrics(e.target.value.split(",").map(x=>x.trim()))}/></label></div><div className="manual-grid"><div className="manual-head"><b>Student</b><b>Attendance</b>{metrics.filter(Boolean).map(m=><b key={m}>{m}</b>)}</div>{students.map(s=><div className="manual-row" key={s.id}><b>{s.name}</b><select name={`attendance:${s.id}`}><option>present</option><option>absent</option><option>late</option><option>unknown</option></select>{metrics.filter(Boolean).map(m=><input key={m} name={`value:${s.id}:${m}`} placeholder="—"/>)}</div>)}</div><button className="primary full">Save session</button></form></>}
function UploadReview({draft,students,extracting,upload,setDraft,save}:{draft:DraftMatrix|null;students:Student[];extracting:boolean;upload:(f?:File)=>void;setDraft:React.Dispatch<React.SetStateAction<DraftMatrix|null>>;save:()=>void}){if(!draft)return <><h2>Upload reusable report sheet</h2><p>PNG or JPG. One page may contain several dates and different metrics.</p><label className="drop"><input type="file" accept="image/png,image/jpeg" disabled={extracting} onChange={e=>upload(e.target.files?.[0])}/><span>{extracting?"Detecting dates, rows, and cells…":"Choose or drop a sheet photo"}</span><small>Rotated phone photos supported · 10 MB max</small></label></>;return <><h2>Review extracted matrix</h2><div className="sheet-summary"><b>{draft.sheet.school_name||"School not detected"}</b><span>{draft.sheet.class_name}</span><span>{draft.sheet.day_time}</span><span>{draft.sheet.lead_coach&&`Lead: ${draft.sheet.lead_coach}`}</span></div><div className="review-matrix">{draft.sessions.map((s,si)=><section key={`${s.date}:${si}`}><h3><input type="date" value={s.date} onChange={e=>setDraft(d=>d?{...d,sessions:d.sessions.map((x,i)=>i===si?{...x,date:e.target.value}:x)}:d)}/><small>{s.metrics.join(" · ")}</small></h3>{s.records.map((r,ri)=><div className={r.confidence<.6?"review-row low":"review-row"} key={`${r.student_name}:${ri}`}><select value={r.student_id} onChange={e=>setDraft(d=>d?{...d,sessions:d.sessions.map((x,i)=>i===si?{...x,records:x.records.map((y,j)=>j===ri?{...y,student_id:e.target.value}:y)}:x)}:d)}><option value="">Create/map “{r.student_name}”</option>{students.map(st=><option key={st.id} value={st.id}>{st.name}</option>)}</select><select value={r.attendance} onChange={e=>setDraft(d=>d?{...d,sessions:d.sessions.map((x,i)=>i===si?{...x,records:x.records.map((y,j)=>j===ri?{...y,attendance:e.target.value}:y)}:x)}:d)}><option>present</option><option>absent</option><option>late</option><option>unknown</option></select>{s.metrics.map(m=><label key={m}><small>{m}</small><input value={r.values[m]||""} onChange={e=>setDraft(d=>d?{...d,sessions:d.sessions.map((x,i)=>i===si?{...x,records:x.records.map((y,j)=>j===ri?{...y,values:{...y.values,[m]:e.target.value}}:y)}:x)}:d)}/></label>)}</div>)}</section>)}</div><button className="primary full" onClick={save}>Save matrix</button></>}
function StructureForm({save}:{save:(e:FormEvent<HTMLFormElement>)=>void}){return <><h2>Create workspace item</h2><form onSubmit={save}><label>Type<select name="kind"><option value="class">Class</option><option value="semester">Semester</option><option value="school">School</option></select></label><label>Name<input name="name" required/></label><button className="primary full">Create</button></form></>}
