"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type School={id:string;name:string}; type Semester={id:string;school_id:string;name:string}; type ClassRow={id:string;school_id:string;semester_id:string;name:string}; type Student={id:string;class_id:string;name:string};
type Entry={id:string;class_id:string;student_id:string;entry_date:string;attendance:string;marks:number|null;remarks:string|null;source:string;confidence:number|null;students?:{name:string}|null};
type Draft={student_id:string;student_name:string;entry_date:string;attendance:string;marks:string;remarks:string;confidence:number};
const db=createClient(),today=()=>new Date().toISOString().slice(0,10);
export default function ReportApp(){
 const [schools,setSchools]=useState<School[]>([]),[semesters,setSemesters]=useState<Semester[]>([]),[classes,setClasses]=useState<ClassRow[]>([]),[students,setStudents]=useState<Student[]>([]),[entries,setEntries]=useState<Entry[]>([]);
 const [schoolId,setSchoolId]=useState(""),[semesterId,setSemesterId]=useState(""),[classId,setClassId]=useState(""); const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [modal,setModal]=useState<"entry"|"upload"|"roster"|"structure"|null>(null),[editing,setEditing]=useState<Entry|null>(null),[drafts,setDrafts]=useState<Draft[]>([]),[extracting,setExtracting]=useState(false);
 const activeSchool=schools.find(x=>x.id===schoolId),activeSemester=semesters.find(x=>x.id===semesterId),activeClass=classes.find(x=>x.id===classId),visibleSemesters=semesters.filter(x=>x.school_id===schoolId),visibleClasses=classes.filter(x=>x.semester_id===semesterId);
 const loadBase=useCallback(async()=>{setLoading(true);const [a,b,c]=await Promise.all([db.from("schools").select("*").order("created_at"),db.from("semesters").select("*").order("created_at"),db.from("classes").select("*").order("created_at")]);const er=a.error||b.error||c.error;if(er){setError(er.message);setLoading(false);return}setSchools(a.data||[]);setSemesters(b.data||[]);setClasses(c.data||[]);const sid=schoolId||a.data?.[0]?.id||"",sem=semesterId||b.data?.find(x=>x.school_id===sid)?.id||"";setSchoolId(sid);setSemesterId(sem);setClassId(classId||c.data?.find(x=>x.semester_id===sem)?.id||"");setLoading(false)},[schoolId,semesterId,classId]);
 const loadClass=useCallback(async()=>{if(!classId){setStudents([]);setEntries([]);return}const [s,e]=await Promise.all([db.from("students").select("*").eq("class_id",classId).order("name"),db.from("report_entries").select("*,students(name)").eq("class_id",classId).order("entry_date",{ascending:false})]);if(s.error||e.error)setError((s.error||e.error)!.message);else{setStudents(s.data||[]);setEntries((e.data as Entry[])||[])}},[classId]);
 useEffect(()=>{loadBase()},[]);useEffect(()=>{loadClass()},[loadClass]);useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(""),3500);return()=>clearTimeout(t)}},[notice]);
 function chooseSchool(id:string){setSchoolId(id);const sem=semesters.find(x=>x.school_id===id)?.id||"";setSemesterId(sem);setClassId(classes.find(x=>x.semester_id===sem)?.id||"")} function chooseSemester(id:string){setSemesterId(id);setClassId(classes.find(x=>x.semester_id===id)?.id||"")}
 async function saveEntry(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),payload={class_id:classId,student_id:String(f.get("student_id")),entry_date:String(f.get("entry_date")),attendance:String(f.get("attendance")),marks:Number(f.get("marks")),remarks:String(f.get("remarks")||""),source:editing?.source||"manual",review_status:editing?"edited":"confirmed"};if(!editing){const existing=await db.from("report_entries").select("id").eq("student_id",payload.student_id).eq("entry_date",payload.entry_date).maybeSingle();if(existing.data){setError("An entry already exists for this student on this date.");return}}const r=editing?await db.from("report_entries").update(payload).eq("id",editing.id):await db.from("report_entries").insert(payload);if(r.error){setError(r.error.code==="23505"?"An entry already exists for this student on this date.":r.error.message);return}setModal(null);setEditing(null);setNotice(editing?"Entry updated.":"Entry added.");loadClass()}
 async function deleteEntry(id:string){if(!confirm("Delete this report entry?"))return;const {error}=await db.from("report_entries").delete().eq("id",id);if(error)setError(error.message);else{setNotice("Entry deleted.");loadClass()}}
 async function saveRoster(e:FormEvent<HTMLFormElement>){e.preventDefault();const name=String(new FormData(e.currentTarget).get("name")).trim();if(!name)return;const {error}=await db.from("students").insert({class_id:classId,name});if(error)setError(error.message);else{e.currentTarget.reset();setNotice("Student added.");loadClass()}}
 async function renameStudent(s:Student){const name=prompt("Student name",s.name)?.trim();if(name){const {error}=await db.from("students").update({name}).eq("id",s.id);if(error)setError(error.message);else loadClass()}} async function removeStudent(s:Student){if(confirm(`Remove ${s.name} and their report entries?`)){const {error}=await db.from("students").delete().eq("id",s.id);if(error)setError(error.message);else loadClass()}}
 async function addStructure(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),kind=String(f.get("kind")),name=String(f.get("name")).trim();let r;if(kind==="school")r=await db.from("schools").insert({name});else if(kind==="semester")r=await db.from("semesters").insert({name,school_id:schoolId,start_date:f.get("start_date")||null,end_date:f.get("end_date")||null});else r=await db.from("classes").insert({name,school_id:schoolId,semester_id:semesterId});if(r.error)setError(r.error.message);else{setModal(null);setNotice(`${kind} created.`);loadBase()}}
 async function upload(file?:File){if(!file)return;if(!/^image\/(png|jpeg)$/.test(file.type)){setError("Please upload an image file (PNG, JPG).");return}setExtracting(true);setError("");try{const body=new FormData();body.append("image",file);body.append("classId",classId);body.append("date",today());const res=await fetch("/api/extract",{method:"POST",body}),json=await res.json();if(!res.ok)throw new Error(json.error||"Extraction failed. You can add entries manually.");const rows:Draft[]=(json.entries||[]).map((x:{student_name:string;attendance:string;marks:number;remarks:string;confidence:number})=>{const exact=students.find(s=>s.name.toLowerCase()===String(x.student_name).toLowerCase());return{student_id:exact?.id||"",student_name:x.student_name||"Unknown",entry_date:json.date||today(),attendance:x.attendance||"present",marks:String(x.marks??""),remarks:x.remarks||"",confidence:Number(x.confidence||0)}}).sort((a:Draft,b:Draft)=>a.confidence-b.confidence);setDrafts(rows);if(!rows.length)setError("No entries detected. Check image quality or add manually.")}catch(x){setError(x instanceof Error?x.message:"Extraction failed. You can add entries manually.")}finally{setExtracting(false)}}
 async function saveDrafts(){for(const d of drafts){let sid=d.student_id;if(!sid){const r=await db.from("students").insert({class_id:classId,name:d.student_name}).select().single();if(r.error){setError(r.error.message);return}sid=r.data.id}const prior=await db.from("report_entries").select("id").eq("student_id",sid).eq("entry_date",d.entry_date).maybeSingle();if(prior.data)continue;const r=await db.from("report_entries").insert({class_id:classId,student_id:sid,entry_date:d.entry_date,attendance:d.attendance,marks:Number(d.marks),remarks:d.remarks,source:"ai_extracted",confidence:d.confidence,review_status:"edited"});if(r.error){setError(r.error.message);return}}setDrafts([]);setModal(null);setNotice("Extracted entries saved without duplicates.");loadClass()}
 if(loading)return <main className="center"><span className="spinner"/>Loading school reports…</main>;
 return <main className="shell"><aside><div className="brand"><span>SR</span><div><b>School Reports</b><small>Coach record workspace</small></div></div><label>School</label><select value={schoolId} onChange={e=>chooseSchool(e.target.value)}>{schools.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label>Semester</label><select value={semesterId} onChange={e=>chooseSemester(e.target.value)}>{visibleSemesters.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="nav-title"><label>Class tabs</label><button className="icon" onClick={()=>setModal("structure")}>+</button></div><nav>{visibleClasses.map(x=><button className={classId===x.id?"active":""} onClick={()=>setClassId(x.id)} key={x.id}>{x.name}</button>)}</nav><button className="ghost full" onClick={()=>setModal("structure")}>+ Add workspace item</button></aside>
 <section className="content"><header><div><p className="crumb">{activeSchool?.name} / {activeSemester?.name}</p><h1>{activeClass?.name||"Choose a class"}</h1><p>{students.length} students · {entries.length} report entries</p></div><div className="actions"><button className="ghost" onClick={()=>setModal("roster")} disabled={!classId}>Manage roster</button><button className="primary" onClick={()=>{setDrafts([]);setModal("upload")}} disabled={!classId}>Upload report</button></div></header>{notice&&<div className="notice">✓ {notice}</div>}{error&&<div className="error">{error}<button onClick={()=>setError("")}>×</button></div>}<div className="tabs">{visibleClasses.map(x=><button className={classId===x.id?"selected":""} onClick={()=>setClassId(x.id)} key={x.id}>{x.name}</button>)}</div>
 <div className="card"><div className="card-head"><div><h2>Daily report entries</h2><p>Marks, attendance, and coach notes</p></div><button className="primary" onClick={()=>{setEditing(null);setModal("entry")}} disabled={!students.length}>+ Add entry</button></div>{!classId?<Empty title="No class selected" text="Create or choose a class tab to begin."/>:entries.length===0?<Empty title="No entries yet" text="Upload a report or add one manually."/>:<div className="table-wrap"><table><thead><tr><th>Date</th><th>Student</th><th>Attendance</th><th>Marks</th><th>Remarks</th><th>Source</th><th/></tr></thead><tbody>{entries.map(x=><tr key={x.id}><td>{new Date(x.entry_date+"T00:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</td><td><b>{x.students?.name}</b></td><td><span className={`pill ${x.attendance}`}>{x.attendance}</span></td><td className="mark">{x.marks??"—"}</td><td>{x.remarks||"—"}</td><td><span className="source">{x.source==="ai_extracted"?`AI ${x.confidence?Math.round(x.confidence*100)+"%":""}`:"Manual"}</span></td><td className="row-actions"><button onClick={()=>{setEditing(x);setModal("entry")}}>Edit</button><button onClick={()=>deleteEntry(x.id)}>Delete</button></td></tr>)}</tbody></table></div>}</div></section>
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&(setModal(null),setEditing(null))}><div className="modal"><button className="close" onClick={()=>{setModal(null);setEditing(null)}}>×</button>{modal==="entry"&&<EntryForm editing={editing} students={students} save={saveEntry}/>} {modal==="roster"&&<><h2>Student roster</h2><p>Add, rename, or remove students in {activeClass?.name}.</p><form className="inline" onSubmit={saveRoster}><input name="name" placeholder="Student name" required/><button className="primary">Add</button></form><div className="roster">{students.map(s=><div key={s.id}><span>{s.name}</span><span><button onClick={()=>renameStudent(s)}>Rename</button><button onClick={()=>removeStudent(s)}>Remove</button></span></div>)}</div></>}{modal==="structure"&&<StructureForm save={addStructure}/>} {modal==="upload"&&<UploadPanel drafts={drafts} students={students} extracting={extracting} upload={upload} setDrafts={setDrafts} save={saveDrafts}/>}</div></div>}</main>
}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div className="empty-icon">↥</div><h3>{title}</h3><p>{text}</p></div>}
function EntryForm({editing,students,save}:{editing:Entry|null;students:Student[];save:(e:FormEvent<HTMLFormElement>)=>void}){return <><h2>{editing?"Edit entry":"Add report entry"}</h2><p>Save a student’s daily marks and attendance.</p><form onSubmit={save}><label>Student<select name="student_id" defaultValue={editing?.student_id} required>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="grid"><label>Date<input name="entry_date" type="date" defaultValue={editing?.entry_date||today()} required/></label><label>Attendance<select name="attendance" defaultValue={editing?.attendance||"present"}><option>present</option><option>absent</option><option>late</option></select></label></div><label>Marks<input name="marks" type="number" step="0.01" defaultValue={editing?.marks??""} required/></label><label>Remarks<textarea name="remarks" defaultValue={editing?.remarks||""}/></label><button className="primary full">Save entry</button></form></>}
function StructureForm({save}:{save:(e:FormEvent<HTMLFormElement>)=>void}){return <><h2>Create workspace item</h2><p>Add another school, semester, or class tab.</p><form onSubmit={save}><label>Type<select name="kind"><option value="class">Class</option><option value="semester">Semester</option><option value="school">School</option></select></label><label>Name<input name="name" required placeholder="e.g. Grade 6 English"/></label><div className="grid"><label>Start date<input name="start_date" type="date"/></label><label>End date<input name="end_date" type="date"/></label></div><button className="primary full">Create</button></form></>}
function UploadPanel({drafts,students,extracting,upload,setDrafts,save}:{drafts:Draft[];students:Student[];extracting:boolean;upload:(f?:File)=>void;setDrafts:React.Dispatch<React.SetStateAction<Draft[]>>;save:()=>void}){return <><h2>Upload coach report</h2><p>Choose a clear PNG or JPG. Review every extracted row before saving.</p>{!drafts.length?<label className="drop"><input type="file" accept="image/png,image/jpeg" disabled={extracting} onChange={e=>upload(e.target.files?.[0])}/><span>{extracting?"Reading handwriting…":"Drop or choose a report image"}</span><small>PNG or JPG · one class report</small></label>:<><div className="review">{drafts.map((d,i)=><div className={d.confidence<.6?"low":""} key={i}><label>Student<select value={d.student_id} onChange={e=>setDrafts(v=>v.map((x,j)=>j===i?{...x,student_id:e.target.value}:x))}><option value="">Create “{d.student_name}”</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Marks<input value={d.marks} onChange={e=>setDrafts(v=>v.map((x,j)=>j===i?{...x,marks:e.target.value}:x))}/></label><label>Attendance<select value={d.attendance} onChange={e=>setDrafts(v=>v.map((x,j)=>j===i?{...x,attendance:e.target.value}:x))}><option>present</option><option>absent</option><option>late</option></select></label><span className="confidence">{Math.round(d.confidence*100)}%</span></div>)}</div><button className="primary full" onClick={save}>Save all entries</button></>}</>}
